// Generated by CoffeeScript 1.6.3
(function() {
  var http, router, server;

  http = require('http');

  server = require('./server');

  router = require('./router');

  http.createServer(server.start(router.route)).listen(1337);

}).call(this);
