// Generated by CoffeeScript 1.6.3
(function() {
  var start, stop;

  start = function() {
    return 'handle start method';
  };

  stop = function() {
    return 'handle stop method.';
  };

  exports.start = start;

  exports.stop = stop;

}).call(this);
