// Generated by CoffeeScript 1.6.3
(function() {
  var route;

  route = function(handler) {
    if (typeof handler !== 'function') {
      return 'mehtod ' + handler + ' is not supported.';
    } else {
      return handler();
    }
  };

  exports.route = route;

}).call(this);
